Fix compilation error: replace unavailable Material Icons
Replace KeyboardArrowUp/KeyboardArrowDown with ExpandLess/ExpandMore
icons which are available in the default Material Icons set.